column_width = 140
indent_width = 4
indent_type = 'Tabs'                  # Tabs, Spaces
quote_style = 'AutoPreferSingle'      # AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle
collapse_simple_statement = 'Always'  # Never, FunctionOnly, ConditionalOnly, Always
call_parentheses = 'None'             # Always, NoSingleString, NoSingleTable, None, Input

[sort_requires]
enabled = true
